name: Build LaTeX document
on: [push]
env:
  target: master
  ref:    ${GITHUB_REF#refs/heads/}
jobs:
  build-head-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          compiler:  make
          args: VERBOSE=1 TARGET=${{ env.target }}
          root_file: ${{ env.target }}.pdf
      - name: Copy to ref-suffixed file
        run: cp ${{ env.target }}.pdf ${{ env.target }}-${{ steps.extract_branch.outputs.branch }}.pdf
      - name: Store compiled PDF artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.target }}-${{ steps.extract_branch.outputs.branch }}.pdf
          path: ${{ env.target }}-${{ steps.extract_branch.outputs.branch }}.pdf
          if-no-files-found: error
